# **Modelo Regresión**

In [ ]:
#Importamos las librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Para este ejemplo utilizaremos un conjunto de datos de una colección de vinos con 13 variables independientes y una variable dependiente, que nos da la clasificación del vino. Las variables independientes son valores característicos del vino en cuestión y que van desde el alcohol, el aroma, el sabor, la acidez, y otros componentes o ingredientes que clasifican un vino.

In [ ]:
url='https://raw.githubusercontent.com/Geerdata/DS/main/Datacoder/Arc.%20Modelo/Wine.csv'
dataset= pd.read_csv(url,sep=',')
dataset.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

Una vez que importamos los datos, separamos las variables independientes en la matriz X y la variable dependiente en el vector y.

In [ ]:
dataset.Customer_Segment.unique()

array([1, 2, 3])

In [ ]:
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

Ahora dividimos el conjunto de datos en dos conjuntos para entrenamiento y prueba:

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Nuestro siguiente paso será estandarizar las escalas para las 13 variables analizadas!

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
Reg_Log = LogisticRegression(random_state = 0)
Reg_Log.fit(X_train, y_train)

# Predicting the Test set results
y_pred = Reg_Log.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
print('El r^2 es:',r2_score(y_test,y_pred))

El r^2 es: 1.0


# **PCA Regresión Con 2 Variables**

In [ ]:
#Importamos las librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Para este ejemplo utilizaremos un conjunto de datos de una colección de vinos con 13 variables independientes y una variable dependiente, que nos da la clasificación del vino. Las variables independientes son valores característicos del vino en cuestión y que van desde el alcohol, el aroma, el sabor, la acidez, y otros componentes o ingredientes que clasifican un vino.

In [ ]:
url='https://raw.githubusercontent.com/Geerdata/DS/main/Datacoder/Arc.%20Modelo/Wine.csv'
dataset= pd.read_csv(url,sep=',')
dataset.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

Una vez que importamos los datos, separamos las variables independientes en la matriz X y la variable dependiente en el vector y.

In [ ]:
dataset.Customer_Segment.unique()

array([1, 2, 3])

In [ ]:
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

Ahora dividimos el conjunto de datos en dos conjuntos para entrenamiento y prueba:

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Nuestro siguiente paso será estandarizar las escalas para las 13 variables analizadas!

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [ ]:
# Explicación de la varianza de las componentes
explained_variance = pca.explained_variance_ratio_
explained_variance

#El primero componente explica el 36.9% de la variabilidad de mis datos y el segundo el 19.3%

array([0.36884109, 0.19318394, 0.10752862, 0.07421996, 0.06245904,
       0.04909   , 0.04117287, 0.02495984, 0.02308855, 0.01864124,
       0.01731766, 0.01252785, 0.00696933])

Una vez con los datos normalizados, aplicamos el PCA para reducir la dimensión de 13 a 2 variables.

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

El conjunto de entrenamiento quedó ahora con 2 variables de la siguiente manera:

Para comprobar que las dos componentes resultantes representan a las 13 variables originales vamos a hacer la predicción de la variable dependiente con la regresión logística, comprobando los resultados de predicción con la matriz de confusión:

In [ ]:
from sklearn.linear_model import LogisticRegression
Reg_Log = LogisticRegression(random_state = 0)
Reg_Log.fit(X_train, y_train)

# Predicting the Test set results
y_pred = Reg_Log.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
print('El r^2 es:',r2_score(y_test,y_pred))

El r^2 es: 0.9451219512195121


# **PCA Regresión Con 3 Variables**

In [ ]:
#Importamos las librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Para este ejemplo utilizaremos un conjunto de datos de una colección de vinos con 13 variables independientes y una variable dependiente, que nos da la clasificación del vino. Las variables independientes son valores característicos del vino en cuestión y que van desde el alcohol, el aroma, el sabor, la acidez, y otros componentes o ingredientes que clasifican un vino.

In [ ]:
url='https://raw.githubusercontent.com/Geerdata/DS/main/Datacoder/Arc.%20Modelo/Wine.csv'
dataset= pd.read_csv(url,sep=',')
dataset.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

Una vez que importamos los datos, separamos las variables independientes en la matriz X y la variable dependiente en el vector y.

In [ ]:
dataset.Customer_Segment.unique()

array([1, 2, 3])

In [ ]:
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

Ahora dividimos el conjunto de datos en dos conjuntos para entrenamiento y prueba:

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Nuestro siguiente paso será estandarizar las escalas para las 13 variables analizadas!

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [ ]:
# Explicación de la varianza de las componentes
explained_variance = pca.explained_variance_ratio_
explained_variance

#El primero componente explica el 36.9% de la variabilidad de mis datos y el segundo el 19.3%

array([0.36884109, 0.19318394, 0.10752862, 0.07421996, 0.06245904,
       0.04909   , 0.04117287, 0.02495984, 0.02308855, 0.01864124,
       0.01731766, 0.01252785, 0.00696933])

Una vez con los datos normalizados, aplicamos el PCA para reducir la dimensión de 13 a 2 variables.

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

El conjunto de entrenamiento quedó ahora con 2 variables de la siguiente manera:

Para comprobar que las dos componentes resultantes representan a las 13 variables originales vamos a hacer la predicción de la variable dependiente con la regresión logística, comprobando los resultados de predicción con la matriz de confusión:

In [ ]:
from sklearn.linear_model import LogisticRegression
Reg_Log = LogisticRegression(random_state = 0)
Reg_Log.fit(X_train, y_train)

# Predicting the Test set results
y_pred = Reg_Log.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
print('El r^2 es:',r2_score(y_test,y_pred))

El r^2 es: 1.0
